### ISSUE TITLE
ImageNode: Setting a size of (0, 0) has unexpected results

### ISSUE THREAD

**Issue by klemmster** [libavg/libavg#494]
Setting (0, 0) as size in a ImageNode constructor doesn't 'hide' the image, but rather shows it at it's full media size.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from libavg import avg, player

canvas = player.createMainCanvas(size=(160,120))
rootNode = canvas.getRootNode()
divNode = avg.DivNode(pos=(40,30), parent=rootNode)
avg.ImageNode(pos=(40,30), size=(0, 0), href="rgb24-64x64.png", parent=divNode)
player.play()
```

Expected behaviour would be, that the images isn't shown. 
use case: simple scaling animation from 0, 0 to mediaSize.

**Comment by uzadow** [comment]
@klemmster: Looking at this again, if you'd like to change/fix this, just go ahead. I believe the 'API change' is so small no-one will be affected.
Maybe just changing the default to (-1,-1) would work?

**Comment by Riin** [comment]
Hello,

since this issue is open and i got a similiar problem, i will post my problem in this thread rather than open a new one.

I want to shrink an image to a touch event center until it disappears with an Animation. But if i animate the picture to change its size to zero, at the end of the animation it will expand to its original size again. It seems that 0 is not acceptable as a width or height value. But thats what i need to do.

There is my mwe code:

    from libavg import player, app
    from libavg import ImageNode, ParallelAnim, LinearAnim
    
    class ExampleDiv(app.MainDiv):
        def onInit(self):
            self.image = ImageNode(parent=self, pos=(0, 0), href='img/scadaA.gif')
            player.subscribe(player.KEY_UP, self.__on_key_up)
    
        def __on_key_up(self, event):
            if event.keystring == 's':
                self.start_shrink()
    
        def start_shrink(self):
            duration = 300
            start_width = self.image.width
            start_height = self.image.height
            start_pos = self.image.pos
            end_pos = self.image.pivot
            animObj = ParallelAnim([
                LinearAnim(self.image, "width", duration, start_width, 1),  # cannot be set to 0
                 LinearAnim(self.image, "height", duration, start_height, 1),  # cannot be set to 0
                 LinearAnim(self.image, "pos", duration, start_pos, end_pos)
            ])
    
            def start_anim():
                keep_old_attr = False
                animObj.start(keep_old_attr)
    
            player.setTimeout(0, start_anim)
    
    if __name__ == "__main__":
        mainDiv = ExampleDiv()
        lib_app = app.App()
        lib_app.run(mainDiv, app_resolution='1024x768')

**Comment by uzadow** [comment]
I just tried to change the default to (-1,-1) and realized that this isn't easy, because the behaviour of  DivNode is that size=(0,0) means it doesn't crop at all - and that would have to change as well. Unfortunately, there is user code depending on this, which would break.

I've updated the documentation to reflect the current behaviour, and I'll close the bug as 'wontfix' - sorry.

@Riin: An easy workaround for your issue is to animate to (0.01,0.01). That should make the node disappear as well.
