### ISSUE TITLE
Better color API

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#570]
* Allow tuples and color names.
* Enable color interpolation.

**Comment by adammhaile** [comment]
I know most of your code is in C so this may not be of help, but thought I would mention it...
My animation library (BiblioPixel) already uses tuples and colors names for all color values so I thought the code I already wrote might be able to save you a little development time: https://github.com/ManiacalLabs/BiblioPixel/blob/master/bibliopixel/colors.py 

It already as a bunch of useful conversion methods and all the HTML color names pre-defined. Since it's all in pure python, everything is written to work with byte values and bitwise operations to keep things fast.
