### ISSUE TITLE
Video Resize and Decode to byte stream

### ISSUE THREAD

**Issue by adammhaile** [libavg/libavg#639]
I would have posted this on the forum, but the account registration seems to be broken.

Two things:

a) is there a way to resize a video being played with VideoNode? I could not find any options.

b) Would it be possible to play a video and at the same time output each frame's byte data to another output stream? I want to display it on a large LED display. But it's pretty low res, so could I play the full res version on my computer screen but then output a really resized byte stream (just RGB pixel data) to my display? All I need is an array of bytes and my code handles the rest.

**Comment by uzadow** [comment]
Thanks for mentioning the account registration bug - I've opened a separate issue (#640) and we'll look into it.

a) Just set the node's size, e.g.: videonode.size = (120,90)
b) You should be able to get the byte array of the resized image by rendering it to an OffscreenCanvas and taking a screenshot every frame.Since it's low-res, the performance should be sufficient.

**Comment by adammhaile** [comment]
Ok, thanks for the suggestion.
