### ISSUE TITLE
LineNodes werfen keine Events

### ISSUE THREAD

**Issue by DjStorm** [libavg/libavg#664]
Hallo Herr Zadow,
ich arbeite zurzeit viel mit ihrem libAVG-Framework und wollte mich zunächst einmal für dieses tolle frei zugängliche Framework bedanken!

Bei der Arbeit mit "LineNode" ist mir aufgefallen, dass keine Input-Callbacks geworfen werden (also: Over, Out, Down, Up, Motion - wenn man diese subscribed hat). Auch wenn der Parameter "sensitive" auf True gesetzt wird, werden keine Events geworfen.

Ist dies so vorgesehen, oder handelt es sich um einen Bug? In jedem Fall wäre diese Funktion wichtig für mein Projekt, da ich recht häufig Events auf LineNodes erkennen müsste.

Liebe Grüße
Maximilian Gräf

**Comment by uzadow** [comment]
This is an international forum, so please stick to English.
Currently, all VectorNodes don't do hit tests on the strokes - only on the fill areas. I can't promise that I'll have time to improve that.
I'm closing this report because the language is wrong. If you'd like me to look at it, please write another report in English.
