### ISSUE TITLE
1.8.2 fails to build in Ubuntu and Debian with ffmpeg 4

### ISSUE THREAD

**Issue by rikmills** [libavg/libavg#805]
Transition to ffmpeg 4 is under way in Ubuntu and Debian, and 1.8.3 fails to build with ffmpeg 4

https://bugs.launchpad.net/ubuntu/+source/libavg/+bug/1785054

https://launchpad.net/ubuntu/+source/libavg/1.8.2-1build2/+build/15146702

Thank in advance

https://github.com/libavg/libavg/pull/804/commits

does not seem to apply cleanly

**Comment by scotty007** [comment]
Thanks for the report!

The failed build (report) in the link is caused by a boost-thread config issue (missing linker flag -lpthread) and not related to ffmpeg.
Current master builds on Debian 9 and 10, Ubuntu 16.04, 18.04 and 20.04.
And maybe there's a new libavg release in the (near?) future ...

Can this be closed or are there any objections?
